name: aia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  http: ^1.3.0
  iconsax: ^0.0.8
  chat_bubbles: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: sv-pro
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.otf
